## Write a Numpy program to compute the multiplication of two given matrixes

In [2]:
import numpy as np

In [8]:
def multiplication_two_matrixes(a,b):
    return np.a.dot(b)            ## compute the multiplication of two given matrixes

a=np.array([[1,2],[3,4]])
b=np.array([[5,4],[5,7]])
c=a.dot(b)
    

In [9]:
c

array([[15, 18],
       [35, 40]])

## Write a NumPy program to compute the determinant of a given square array

In [10]:
def  determinant_square_array(a):
    return np.linalg.det(a)      ##compute the determinant of a given square array
a=np.array([[1,4],[2,7]])
a1=np.linalg.det(a)

In [11]:
a1

-1.0

## Write a NumPy program to compute the cross product of two given vectors

In [19]:
def cross_product_of_two_vectors(v1,v2):     
    return np.cross(v1,v2)       ##compute the cross product of two given vectors

v1=np.array([1,8,5])
v2=np.array([9,3,6])
v=np.cross(v1,v2)

In [20]:
v

array([ 33,  39, -69])

## Write a NumPy program to compute the condition number of a given matrix

In [24]:
##compute the condition number of a given matrix
def condition_matrix(q): 
    return np.linalg.cond(q)
q=np.array([[4,9,3],[0,4,2]])
q1=np.linalg.cond(q)            

In [23]:
q1

6.524723443121696

## Write a NumPy program to compute the inverse of a given matrix

In [14]:
def inverse_of_matrix(matrix):
    return np.linalg.inv(matrix)    ## compute the inverse of a given matrix

matrix=np.array([[6,5,1],
                [9,7,4],[2,4,7]])
matrix1=np.linalg.inv(matrix)

In [15]:
matrix1

array([[-0.6       ,  0.56363636, -0.23636364],
       [ 1.        , -0.72727273,  0.27272727],
       [-0.4       ,  0.25454545,  0.05454545]])